pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
    actions:
      merge:
        method: merge
  - name: automatic merge on Github Action success if some files are changed
    conditions:
      - check-success=build
      - files~=^./
    actions:
      merge:
        method: merge
  - name: say hi on Pull Request
    conditions:
      - author!=a
    actions:
      comment:
        message: |
          感谢您提出Pull Request，我会尽快Review。我会在1-2日内进行查看或者回复，如果遇到节假日可能会处理较慢，敬请谅解。
  - name: ask to resolve conflict
    conditions:
      - conflict
    actions:
      comment:
        message: 这个 PR 发生了冲突. @{{author}} 是否能帮忙修复呢? 🙏
  - name: ask to fix commit message
    conditions:
      - check-failure=Semantic Pull Request
    actions:
      comment:
        message: |
          这个 PR 发生了检查失败，@{{author}} 是否能帮忙修复呢？🙏pull_request_rules: